'''Problem 32: Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.'''


import string
def mutate(x):
	result= list()
	alphabets=string.ascii_lowercase
	[result.append(x[:i]+x[i+1:]) for i in range(len(x))]#delete
	[result.append(x[:i]+alpha+x[i:]) for i in range(len(x)+1) for alpha in alphabets]#insert
	[result.append(x[:i]+alpha+x[i+1:]) for i in range(len(x)+1) for alpha in alphabets]#replacing
	[result.append(x[:i]+x[i+1]+x[i]+x[i+2:]) for i in range(len(x)-1)]#swapping
	return result

words=mutate('hello')
print 'helo' in words#delete
print 'helqlo' in words#insert
print 'cello' in words#replacing
print 'helol' in words#swapping
